name: Build
# This action will execute on every push the branch master,
# or when any tag is created that matches 'v{number}.{number}.{number}' i.e. v1.0.0
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on

on:
  workflow_dispatch:
    # inputs:
    #   name:
    #     description: 'Person to greet'
    #     required: true
    #     default: 'Mona the Octocat'
    #   home:
    #     description: 'location'
    #     required: false
    #     default: 'The Octoverse'
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*[0-9a-z]*.*[0-9]*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push to S3 CI
      if: startsWith(github.ref, 'refs/heads/')
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_Access_Key}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_Access_Secret }}
        AWS_REGION: us-east-1
      run: bash scripts/pipeline/release.sh 
      #${{secrets.AWS_Bucket_Name_CI}} "myapp.zip" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} scripts/hello_lambda.zip

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Push to S3 QA
  #     if: startsWith(github.ref, 'refs/tags/')
  #     run: bash scripts/pipeline/release.sh ${{secrets.AWS_Bucket_Name_QA}} "myapp.zip" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "myapp.zip"

      # - name: .NET Lambda build and deploy
      # uses: evalytica/dotnet-lambda-actions/deploy@v0.1.0
      # env:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   AWS_REGION: us-east-1