name: Continuous Integration

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2

    - run: mkdir -p downloads

    - run: echo hello satish > downloads/alpha.html
    - run: echo hello satish > downloads/bravo.html
    - run: echo hello satish > downloads/charlie.html
   

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: downloads
