name: Continuous Integration

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./AspNetMonsters.ApplicationInsights
    - name: Test
      run: dotnet test
      working-directory: ./AspNetMonsters.ApplicationInsights
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          dist
          !dist/**/*.md
