name: Deploy to dev environment
on:
  push:
    branches:
      - main

  pull_request:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use .NET 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.500

    - name: .NET Lambda build and deploy
      uses: evalytica/dotnet-lambda-actions/deploy@v0.1.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
        AWS_REGION: us-west-2
        DOTNET_LAMBDA_PACKAGE_NAME: latest.zip
        # DOTNET_LAMBDA_FUNCTION_HANDLER: Host::MyLambdaDomain.Host.LambdaEntryPoint::FunctionHandlerAsync
        # DOTNET_LAMBDA_FUNCTION_NAME: my-lambda-function-name
        DOTNET_LAMBDA_S3_LOCATION: AWS_BUCKET_NAME_CI
        DOTNET_LAMBDA_WORKING_DIR: ./src